export const copart = [
  { port: 'CA', value: 1800, location: 'AK - Anchorage' },
  { port: 'GA', value: 350, location: 'AL - Birmingham' },
  { port: 'GA', value: 400, location: 'AL - Mobile' },
  { port: 'GA', value: 350, location: 'AL - Montgomery' },
  { port: 'GA', value: 375, location: 'AL - Tanner' },
  { port: 'GA', value: 350, location: 'AL - Dothan' },
  { port: 'TX', value: 475, location: 'AR - Fayetteville' },
  { port: 'TX', value: 400, location: 'AR - Little Rock' },
  { port: 'CA', value: 350, location: 'AZ - Phoenix' },
  { port: 'CA', value: 400, location: 'AZ - Tucson' },
  { port: 'CA', value: 350, location: 'CA - Antelope' },
  { port: 'CA', value: 275, location: 'CA - Bakersfield' },
  { port: 'CA', value: 350, location: 'CA - Crashedtoys Sacramento' },
  { port: 'CA', value: 300, location: 'CA - Fresno' },
  { port: 'CA', value: 375, location: 'CA - Hayward' },
  { port: 'CA', value: 175, location: 'CA - Long Beach' },
  { port: 'CA', value: 175, location: 'CA - Los Angeles' },
  { port: 'CA', value: 375, location: 'CA - Martinez' },
  { port: 'CA', value: 200, location: 'CA - Rancho Cucamonga' },
  { port: 'CA', value: 375, location: 'CA - Sacramento' },
  { port: 'CA', value: 225, location: 'CA - San Bernardino' },
  { port: 'CA', value: 250, location: 'CA - San Diego' },
  { port: 'CA', value: 375, location: 'CA - San Jose' },
  { port: 'CA', value: 400, location: 'CA - So Sacramento' },
  { port: 'CA', value: 225, location: 'CA - Sun Valley' },
  { port: 'CA', value: 375, location: 'CA - Vallejo' },
  { port: 'CA', value: 200, location: 'CA - Van Nuys' },
  { port: 'CA', value: 450, location: 'CA - Redding' },
  { port: 'CA', value: 700, location: 'CO - Colorado Springs' },
  { port: 'TX', value: 650, location: 'CO - Denver' },
  { port: 'TX', value: 650, location: 'CO - Denver Central' },
  { port: 'TX', value: 650, location: 'CO - Denver South' },
  { port: 'NJ', value: 275, location: 'CT - Hartford' },
  { port: 'NJ', value: 275, location: 'CT - Hartford Springfield' },
  { port: 'NJ', value: 350, location: 'DE - Seaford' },
  { port: 'GA', value: 175, location: 'FL - Jacksonville East' },
  { port: 'GA', value: 250, location: 'FL - Jacksonville West' },
  { port: 'GA', value: 250, location: 'FL - Jacksonville North' },
  { port: 'GA', value: 275, location: 'FL - Orlando North' },
  { port: 'GA', value: 275, location: 'FL - Orlando South' },
  { port: 'GA', value: 350, location: 'FL - Ft. Pierce' },
  { port: 'GA', value: 275, location: 'FL - Miami Central' },
  { port: 'GA', value: 275, location: 'FL - Miami North' },
  { port: 'GA', value: 275, location: 'FL - Miami South' },
  { port: 'GA', value: 300, location: 'FL - Ocala' },
  { port: 'GA', value: 350, location: 'FL - Punta Gorda' },
  { port: 'GA', value: 350, location: 'FL - Tallahassee' },
  { port: 'GA', value: 275, location: 'FL - Tampa South' },
  { port: 'GA', value: 300, location: 'FL - West Palm Beach' },
  { port: 'GA', value: 250, location: 'GA - Atlanta East' },
  { port: 'GA', value: 250, location: 'GA - Atlanta North' },
  { port: 'GA', value: 250, location: 'GA - Atlanta South' },
  { port: 'GA', value: 250, location: 'GA - Atlanta West' },
  { port: 'GA', value: 250, location: 'GA - Cartersville' },
  { port: 'GA', value: 200, location: 'GA - CrashedToys Atlanta' },
  { port: 'GA', value: 250, location: 'GA - Macon' },
  { port: 'GA', value: 150, location: 'GA - Savannah' },
  { port: 'GA', value: 275, location: 'GA - Tifton' },
  { port: 'CA', value: 1800, location: 'HI - Honolulu' },
  { port: 'NJ', value: 650, location: 'IA - Davenport' },
  { port: 'NJ', value: 650, location: 'IA - Des Moines' },
  { port: 'CA', value: 675, location: 'ID - Boise' },
  { port: 'NJ', value: 550, location: 'IL - Chicago North' },
  { port: 'NJ', value: 550, location: 'IL - Chicago South' },
  { port: 'NJ', value: 550, location: 'IL - Peoria' },
  { port: 'NJ', value: 550, location: 'IL - Southern Illinois' },
  { port: 'NJ', value: 550, location: 'IL - Wheeling' },
  { port: 'NJ', value: 600, location: 'IN - Fort Wayne' },
  { port: 'NJ', value: 550, location: 'IN - Hammond' },
  { port: 'NJ', value: 500, location: 'IN - Indianapolis' },
  { port: 'NJ', value: 625, location: 'IN - Cicero' },
  { port: 'NJ', value: 550, location: 'KS - Kansas City' },
  { port: 'TX', value: 600, location: 'KS - Wichita' },
  { port: 'GA', value: 550, location: 'KY - Lexington East' },
  { port: 'GA', value: 550, location: 'KY - Lexington West' },
  { port: 'NJ', value: 525, location: 'KY - Walton' },
  { port: 'TX', value: 300, location: 'LA - Baton Rouge' },
  { port: 'TX', value: 350, location: 'LA - New Orleans' },
  { port: 'TX', value: 325, location: 'LA - Shreveport' },
  { port: 'NJ', value: 350, location: 'MA - North Boston' },
  { port: 'NJ', value: 350, location: 'MA - South Boston' },
  { port: 'NJ', value: 300, location: 'MA - West Warren' },
  { port: 'NJ', value: 300, location: 'MD - Baltimore' },
  { port: 'NJ', value: 275, location: 'MD - Baltimore East' },
  { port: 'NJ', value: 275, location: 'DC - Washington DC' },
  { port: 'NJ', value: 450, location: 'ME - Lyman' },
  { port: 'NJ', value: 550, location: 'MI - Detroit' },
  { port: 'NJ', value: 550, location: 'MI - Flint' },
  { port: 'NJ', value: 575, location: 'MI - Ionia' },
  { port: 'NJ', value: 900, location: 'MI - Kincheloe' },
  { port: 'NJ', value: 650, location: 'MI - Lansing' },
  { port: 'NJ', value: 550, location: 'MN - CrashedToys Minneapolis' },
  { port: 'NJ', value: 550, location: 'MN - Minneapolis' },
  { port: 'NJ', value: 550, location: 'MN - Minneapolis North' },
  { port: 'NJ', value: 650, location: 'MN - St. Cloud' },
  { port: 'GA', value: 575, location: 'MO - Springfield' },
  { port: 'NJ', value: 675, location: 'MO - Columbia' },
  { port: 'NJ', value: 700, location: 'MO - Sikeston' },
  { port: 'NJ', value: 600, location: 'MO - St. Louis' },
  { port: 'GA', value: 450, location: 'MS - Jackson' },
  { port: 'CA', value: 115, location: 'MT - Billings' },
  { port: 'CA', value: 115, location: 'MT - Helena' },
  { port: 'GA', value: 300, location: 'NC - China Grove' },
  { port: 'GA', value: 275, location: 'NC - Lumberton' },
  { port: 'GA', value: 400, location: 'NC - Mebane' },
  { port: 'GA', value: 350, location: 'NC - Mocksville' },
  { port: 'GA', value: 300, location: 'NC - Raleigh' },
  { port: 'GA', value: 300, location: 'NC - Concord' },
  { port: 'NJ', value: 650, location: 'NE - Lincoln' },
  { port: 'NJ', value: 350, location: 'NH - Candia' },
  { port: 'NJ', value: 200, location: 'NJ - Glassboro East' },
  { port: 'NJ', value: 175, location: 'NJ - Somerville' },
  { port: 'NJ', value: 175, location: 'NJ - Trenton' },
  { port: 'NJ', value: 200, location: 'NJ - Glassboro West' },
  { port: 'TX', value: 575, location: 'NM - Albuquerque' },
  { port: 'CA', value: 400, location: 'NV - Las Vegas' },
  { port: 'CA', value: 600, location: 'NV - Reno' },
  { port: 'NJ', value: 275, location: 'NY - Albany' },
  { port: 'NJ', value: 450, location: 'NY - Buffalo' },
  { port: 'NJ', value: 225, location: 'NY - Long Island' },
  { port: 'NJ', value: 250, location: 'NY - Newburgh' },
  { port: 'NJ', value: 375, location: 'NY - Rochester' },
  { port: 'NJ', value: 300, location: 'NY - Syracuse' },
  { port: 'NJ', value: 450, location: 'OH - Cleveland East' },
  { port: 'NJ', value: 450, location: 'OH - Cleveland West' },
  { port: 'NJ', value: 550, location: 'OH - Columbus' },
  { port: 'NJ', value: 500, location: 'OH - Dayton' },
  { port: 'TX', value: 400, location: 'OK - Oklahoma City' },
  { port: 'TX', value: 450, location: 'OK - Tulsa' },
  { port: 'CA', value: 675, location: 'OR - Eugene' },
  { port: 'CA', value: 600, location: 'OR - Portland North' },
  { port: 'CA', value: 600, location: 'OR - Portland South' },
  { port: 'NJ', value: 400, location: 'PA - Altoona' },
  { port: 'NJ', value: 350, location: 'PA - Chambersburg' },
  { port: 'NJ', value: 250, location: 'PA - Harrisburg' },
  { port: 'NJ', value: 200, location: 'PA - Philadelphia' },
  { port: 'NJ', value: 250, location: 'PA - Philadelphia East' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh East' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh West' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh North' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh South' },
  { port: 'NJ', value: 275, location: 'PA - Scranton' },
  { port: 'NJ', value: 300, location: 'PA - York Haven' },
  { port: 'NJ', value: 300, location: 'RI - Exeter' },
  { port: 'GA', value: 250, location: 'SC - Columbia' },
  { port: 'GA', value: 250, location: 'SC - North Charleston' },
  { port: 'GA', value: 275, location: 'SC - Spartanburg' },
  { port: 'GA', value: 350, location: 'TN - Knoxville' },
  { port: 'GA', value: 450, location: 'TN - Memphis' },
  { port: 'GA', value: 400, location: 'TN - Nashville' },
  { port: 'TX', value: 375, location: 'TX - Abilene' },
  { port: 'TX', value: 450, location: 'TX - Amarillo' },
  { port: 'TX', value: 450, location: 'TX - Andrews' },
  { port: 'TX', value: 250, location: 'TX - Austin' },
  { port: 'TX', value: 300, location: 'TX - Corpus Christi' },
  { port: 'TX', value: 250, location: 'TX - CrashedToys Dallas' },
  { port: 'TX', value: 250, location: 'TX - Dallas' },
  { port: 'TX', value: 250, location: 'TX - Dallas South' },
  { port: 'TX', value: 450, location: 'TX - El Paso' },
  { port: 'TX', value: 275, location: 'TX - Ft. Worth TX - Houston' },
  { port: 'TX', value: 200, location: 'TX - Longview' },
  { port: 'TX', value: 250, location: 'TX - Lufkin' },
  { port: 'TX', value: 300, location: 'TX - McAllen' },
  { port: 'TX', value: 275, location: 'TX - San Antonio' },
  { port: 'TX', value: 200, location: 'TX - Houston East' },
  { port: 'TX', value: 300, location: 'TX - Waco' },
  { port: 'CA', value: 500, location: 'UT - Ogden' },
  { port: 'CA', value: 550, location: 'UT - Salt Lake City' },
  { port: 'GA', value: 450, location: 'VA - Danville' },
  { port: 'NJ', value: 300, location: 'VA - Fredericksburg' },
  { port: 'NJ', value: 375, location: 'VA - Hampton' },
  { port: 'NJ', value: 375, location: 'VA - Richmond' },
  { port: 'NJ', value: 375, location: 'VA - Richmond East' },
  { port: 'CA', value: 600, location: 'WA - Graham' },
  { port: 'CA', value: 650, location: 'WA - North Seattle' },
  { port: 'CA', value: 900, location: 'WA - Pasco' },
  { port: 'CA', value: 850, location: 'WA - Spokane ' },
  { port: 'NJ', value: 600, location:	'WI - Appleton' },
  { port: 'NJ', value: 650, location:	'WI - Madison' },
  { port: 'NJ', value: 650, location:	'WI - Milwaukee North' },
  { port: 'NJ', value: 600, location:	'WI - Milwaukee' },
  { port: 'GA', value: 600, location:	'WI - Appleton' },
  { port: 'GA', value: 650, location:	'WI - Madison' },
  { port: 'GA', value: 650, location:	'WI - Milwaukee North' },
  { port: 'GA', value: 600, location:	'WI - Milwaukee' },
  { port: 'NJ', value: 550, location:	'WV - Charleston' },
  { port: 'CA', value: 850, location:	'WY - Casper' }
];

export const iaai = [
  { port: 'CA', value: 2000, location: 'AK - Anchorage' },
  { port: 'GA', value: 350, location: 'AL - ADESA Birmingham' },
  { port: 'GA', value: 375, location: 'AL - Birmingham' },
  { port: 'GA', value: 375, location: 'AL - Dothan' },
  { port: 'GA', value: 375, location: 'AL - Huntsville' },
  { port: 'TX', value: 475, location: 'AR - Fayetteville' },
  { port: 'TX', value: 400, location: 'AR - Little Rock' },
  { port: 'CA', value: 350, location: 'AZ - Phoenix' },
  { port: 'CA', value: 375, location: 'AZ - Tucson' },
  { port: 'CA', value: 250, location: 'CA - ACE - Carson' },
  { port: 'CA', value: 250, location: 'CA - ACE - Perris' },
  { port: 'CA', value: 175, location: 'CA - Anaheim' },
  { port: 'CA', value: 200, location: 'CA - Colton' },
  { port: 'CA', value: 350, location: 'CA - East Bay' },
  { port: 'CA', value: 225, location: 'CA - Fontana' },
  { port: 'CA', value: 325, location: 'CA - Fremont' },
  { port: 'CA', value: 300, location: 'CA - Fresno' },
  { port: 'CA', value: 250, location: 'CA - High Desert' },
  { port: 'CA', value: 175, location: 'CA - Los Angeles' },
  { port: 'CA', value: 175, location: 'CA - North Hollywood' },
  { port: 'CA', value: 375, location: 'CA - Sacramento' },
  { port: 'CA', value: 250, location: 'CA - San Diego' },
  { port: 'TX', value: 575, location: 'CO - Denver' },
  { port: 'TX', value: 575, location: 'CO - Denver East' },
  { port: 'CA', value: 800, location: 'CO - Western Colorado' },
  { port: 'NJ', value: 275, location: 'CT - Hartford' },
  { port: 'NJ', value: 275, location: 'CT - Hartford-South' },
  { port: 'NJ', value: 275, location: 'DE - New Castle' },
  { port: 'GA', value: 300, location: 'FL - Clearwater' },
  { port: 'GA', value: 225, location: 'FL - Jacksonville' },
  { port: 'GA', value: 400, location: 'FL - Pensacola' },
  { port: 'GA', value: 275, location: 'FL - Orlando' },
  { port: 'GA', value: 275, location: 'FL - Orlando-North' },
  { port: 'GA', value: 350, location: 'FL - Fort Myers' },
  { port: 'GA', value: 350, location: 'FL - Fort Pierce' },
  { port: 'GA', value: 275, location: 'FL - Miami' },
  { port: 'GA', value: 275, location: 'FL - Miami-North' },
  { port: 'GA', value: 300, location: 'FL - Tampa' },
  { port: 'GA', value: 300, location: 'FL - Tampa North' },
  { port: 'GA', value: 275, location: 'GA - Atlanta' },
  { port: 'GA', value: 275, location: 'GA - Atlanta East' },
  { port: 'GA', value: 275, location: 'GA - Atlanta North' },
  { port: 'GA', value: 300, location: 'GA - Atlanta South' },
  { port: 'GA', value: 275, location: 'GA - Macon' },
  { port: 'GA', value: 150, location: 'GA - Savannah' },
  { port: 'GA', value: 275, location: 'GA - Tifton' },
  { port: 'CA', value: 2100, location: 'HI - Honolulu' },
  { port: 'NJ', value: 575, location: 'IA - Davenport' },
  { port: 'NJ', value: 600, location: 'IA - Des Moines' },
  { port: 'CA', value: 675, location: 'ID - Boise' },
  { port: 'NJ', value: 575, location: 'IL - Chicago North' },
  { port: 'NJ', value: 575, location: 'IL - Chicago South' },
  { port: 'NJ', value: 575, location: 'IL - Chicago West' },
  { port: 'NJ', value: 600, location: 'IL - Lincoln' },
  { port: 'NJ', value: 575, location: 'IL - Specialty Division' },
  { port: 'NJ', value: 550, location: 'IL - St. Louis' },
  { port: 'NJ', value: 500, location: 'IN - Indianapolis' },
  { port: 'NJ', value: 550, location: 'IN - South Bend' },
  { port: 'NJ', value: 500, location: 'KS - Kansas City' },
  { port: 'TX', value: 475, location: 'KS - Wichita' },
  { port: 'NJ', value: 550, location: 'KY - Ashland' },
  { port: 'GA', value: 550, location: 'KY - Bowling Green' },
  { port: 'GA', value: 500, location: 'KY - Louisville' },
  { port: 'GA', value: 600, location: 'KY - Louisville North' },
  { port: 'GA', value: 500, location: 'KY - Paducah' },
  { port: 'TX', value: 300, location: 'LA - Lafayette' },
  { port: 'TX', value: 275, location: 'LA - Shreveport' },
  { port: 'GA', value: 400, location: 'LA - Baton Rouge' },
  { port: 'GA', value: 350, location: 'LA - New Orleans' },
  { port: 'GA', value: 400, location: 'LA - New Orleans East' },
  { port: 'NJ', value: 350, location: 'MA - Boston - Shirley' },
  { port: 'NJ', value: 275, location: 'MA - Taunton' },
  { port: 'NJ', value: 350, location: 'MA - Templeton' },
  { port: 'NJ', value: 275, location: 'MD - Baltimore' },
  { port: 'NJ', value: 275, location: 'MD - Dundalk' },
  { port: 'NJ', value: 300, location: 'MD - Laurel' },
  { port: 'NJ', value: 275, location: 'MD - Metro DC' },
  { port: 'NJ', value: 425, location: 'ME - Portland - Gorham' },
  { port: 'NJ', value: 475, location: 'MI - Detroit' },
  { port: 'NJ', value: 575, location: 'MI - Flint' },
  { port: 'NJ', value: 650, location: 'MI - Grand Rapids' },
  { port: 'NJ', value: 500, location: 'MN - Minneapolis/St. Paul' },
  { port: 'GA', value: 550, location: 'MO - Springfield' },
  { port: 'NJ', value: 550, location: 'MO - Springfield' },
  { port: 'GA', value: 450, location: 'MS - Grenada' },
  { port: 'GA', value: 375, location: 'MS - Gulf Coast' },
  { port: 'GA', value: 400, location: 'MS - Jackson' },
  { port: 'CA', value: 1150, location: 'MT - Billings' },
  { port: 'CA', value: 1150, location: 'MT - Missoula' },
  { port: 'GA', value: 350, location: 'NC - Asheville' },
  { port: 'GA', value: 275, location: 'NC - Charlotte' },
  { port: 'GA', value: 350, location: 'NC - Concord' },
  { port: 'GA', value: 350, location: 'NC - Greensboro' },
  { port: 'GA', value: 275, location: 'NC - Raleigh' },
  { port: 'GA', value: 300, location: 'NC - Wilmington' },
  { port: 'NJ', value: 900, location: 'ND - Fargo' },
  { port: 'NJ', value: 650, location: 'NE - Omaha' },
  { port: 'NJ', value: 375, location: 'NH - Manchester' },
  { port: 'NJ', value: 175, location: 'NJ - Avenel New Jersey' },
  { port: 'NJ', value: 175, location: 'NJ - Central New Jersey' },
  { port: 'NJ', value: 225, location: 'NJ - Northern New Jersey' },
  { port: 'NJ', value: 225, location: 'NJ - Southern New Jersey' },
  { port: 'NJ', value: 225, location: 'NJ - Englishtown' },
  { port: 'TX', value: 575, location: 'NM - Albuquerque' },
  { port: 'CA', value: 300, location: 'NV - Las Vegas' },
  { port: 'CA', value: 600, location: 'NV - Reno' },
  { port: 'NJ', value: 275, location: 'NY - Albany' },
  { port: 'NJ', value: 450, location: 'NY - Buffalo' },
  { port: 'NJ', value: 250, location: 'NY - Long Island' },
  { port: 'NJ', value: 250, location: 'NY - Newburgh' },
  { port: 'NJ', value: 400, location: 'NY - Rochester' },
  { port: 'NJ', value: 300, location: 'NY - Syracuse' },
  { port: 'NJ', value: 450, location: 'OH - Akron-Canton' },
  { port: 'NJ', value: 500, location: 'OH - Cincinnati' },
  { port: 'NJ', value: 500, location: 'OH - Cincinnati-South' },
  { port: 'NJ', value: 450, location: 'OH - Cleveland' },
  { port: 'NJ', value: 550, location: 'OH - Columbus' },
  { port: 'NJ', value: 500, location: 'OH - Dayton' },
  { port: 'TX', value: 400, location: 'OK - Oklahoma City' },
  { port: 'TX', value: 400, location: 'OK - Tulsa' },
  { port: 'CA', value: 600, location: 'OR - Eugene' },
  { port: 'CA', value: 625, location: 'OR - Portland' },
  { port: 'CA', value: 625, location: 'OR - Portland West' },
  { port: 'NJ', value: 450, location: 'PA - Altoona' },
  { port: 'NJ', value: 275, location: 'PA - Bridgeport' },
  { port: 'NJ', value: 475, location: 'PA - Erie' },
  { port: 'NJ', value: 200, location: 'PA - Philadelphia' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh' },
  { port: 'NJ', value: 400, location: 'PA - Pittsburgh-North' },
  { port: 'NJ', value: 275, location: 'PA - Scranton' },
  { port: 'NJ', value: 275, location: 'PA - York Springs' },
  { port: 'NJ', value: 325, location: 'RI - Providence' },
  { port: 'GA', value: 250, location: 'SC - Charleston' },
  { port: 'GA', value: 250, location: 'SC - Columbia' },
  { port: 'GA', value: 275, location: 'SC - Greenville' },
  { port: 'GA', value: 250, location: 'SC - Lexington' },
  { port: 'NJ', value: 875, location: 'SD - Sioux Falls' },
  { port: 'GA', value: 450, location: 'TN - Chattanooga' },
  { port: 'GA', value: 350, location: 'TN - Knoxville' },
  { port: 'GA', value: 450, location: 'TN - Memphis' },
  { port: 'GA', value: 375, location: 'TN - Nashville' },
  { port: 'TX', value: 350, location: 'TX - Abilene' },
  { port: 'TX', value: 450, location: 'TX - Amarillo' },
  { port: 'TX', value: 250, location: 'TX - Austin' },
  { port: 'TX', value: 300, location: 'TX - Corpus Christi' },
  { port: 'TX', value: 250, location: 'TX - Dallas' },
  { port: 'TX', value: 250, location: 'TX - IAA Dallas/Ft Worth' },
  { port: 'TX', value: 40, location: 'TX - El Paso' },
  { port: 'TX', value: 300, location: 'TX - Fort Worth North' },
  { port: 'TX', value: 175, location: 'TX - Houston' },
  { port: 'TX', value: 150, location: 'TX - Houston South' },
  { port: 'TX', value: 150, location: 'TX - Houston-North' },
  { port: 'TX', value: 275, location: 'TX - Longview' },
  { port: 'TX', value: 450, location: 'TX - Lubbock' },
  { port: 'TX', value: 275, location: 'TX - McAllen' },
  { port: 'TX', value: 450, location: 'TX - Permian Basin' },
  { port: 'TX', value: 275, location: 'TX - San Antonio' },
  { port: 'TX', value: 275, location: 'TX - San Antonio-South' },
  { port: 'CA', value: 500, location: 'UT - Salt Lake City' },
  { port: 'NJ', value: 350, location: 'VA - Culpeper' },
  { port: 'NJ', value: 300, location: 'VA - Fredericksburg-South' },
  { port: 'NJ', value: 300, location: 'VA - Northern Virginia' },
  { port: 'NJ', value: 375, location: 'VA - Pulaski' },
  { port: 'NJ', value: 350, location: 'VA - Richmond' },
  { port: 'NJ', value: 450, location: 'VA - Roanoke' },
  { port: 'NJ', value: 400, location: 'VA - Suffolk' },
  { port: 'NJ', value: 375, location: 'VA - Tidewater' },
  { port: 'NJ', value: 525, location: 'VT - Burlington' },
  { port: 'CA', value: 650, location: 'WA - Seattle' },
  { port: 'CA', value: 850, location: 'WA - Spokane' },
  { port: 'NJ', value: 600, location: 'WI - Appleton' },
  { port: 'NJ', value: 500, location: 'WI - Milwaukee' },
  { port: 'NJ', value: 575, location: 'WI - Portage' },
  { port: 'NJ', value: 600, location: 'WV - Buckhannon' },
  { port: 'NJ', value: 550, location: 'WV - Shady Spring' },
  { port: 'CA', value: 1100, location: 'WY - Casper' }
];
