export const copart = [
  { location: 'AL - Birmingham', port: 'NJ', value: 950 },
  { location: 'AL - Birmingham', port: 'NJ',	value: 950 },
  { location: 'AL - Mobile', port: 'NJ',	value: 1100 },
  { location: 'AL - Montgomery', port: 'NJ',	value: 1000 },
  { location: 'AL - Tanner', port: 'NJ',	value: 1000 },
  { location: 'AL - Dothan', port: 'NJ',	value: 1075 },
  { location: 'AR - Fayetteville', port: 'NJ',	value: 1500 },
  { location: 'AR - Little Rock', port: 'NJ',	value: 1250 },
  { location: 'AZ - Phoenix', port: 'NJ',	value: 1650 },
  { location: 'AZ - Tucson', port: 'NJ',	value: 1750 },
  { location: 'CA - Antelope', port: 'NJ',	value: 1775 },
  { location: 'CA - Bakersfield', port: 'NJ',	value: 1775 },
  { location: 'CA - Crashedtoys Sacramento', port: 'NJ',	value: 1750 },
  { location: 'CA - Fresno', port: 'NJ',	value: 1750 },
  { location: 'CA - Hayward', port: 'NJ',	value: 1700 },
  { location: 'CA - Long Beach', port: 'NJ',	value: 1700 },
  { location: 'CA - Los Angeles', port: 'NJ',	value: 1600 },
  { location: 'CA - Martinez', port: 'NJ',	value: 1750 },
  { location: 'CA - Rancho Cucamonga', port: 'NJ',	value: 1750 },
  { location: 'CA - Sacramento', port: 'NJ',	value: 1775 },
  { location: 'CA - San Bernardino', port: 'NJ',	value: 1650 },
  { location: 'CA - San Diego', port: 'NJ',	value: 1750 },
  { location: 'CA - San Jose', port: 'NJ',	value: 1750 },
  { location: 'CA - So Sacramento', port: 'NJ',	value: 1750 },
  { location: 'CA - Sun Valley', port: 'NJ',	value: 1750 },
  { location: 'CA - Vallejo', port: 'NJ',	value: 1850 },
  { location: 'CA - Van Nuys', port: 'NJ',	value: 1850 },
  { location: 'CA - Redding', port: 'NJ',	value: 1950 },
  { location: 'CO - Colorado Springs', port: 'NJ',	value: 1200 },
  { location: 'CO - Denver', port: 'NJ',	value: 1100 },
  { location: 'CO - Denver Central', port: 'NJ',	value: 1100 },
  { location: 'CO - Denver South', port: 'NJ',	value: 1000 },
  { location: 'CT - Hartford', port: 'NJ',	value: 350 },
  { location: 'CT - Hartford Springfield', port: 'NJ',	value: 350 },
  { location: 'DE - Seaford', port: 'NJ',	value: 400 },
  { location: 'FL - Jacksonville East', port: 'NJ',	value: 775 },
  { location: 'FL - Jacksonville West', port: 'NJ',	value: 775 },
  { location: 'FL - Jacksonville North', port: 'NJ',	value: 775 },
  { location: 'FL - Orlando North', port: 'NJ',	value: 850 },
  { location: 'FL - Orlando South', port: 'NJ',	value: 825 },
  { location: 'FL - Ft. Pierce', port: 'NJ',	value: 825 },
  { location: 'FL - Miami Central', port: 'NJ',	value: 750 },
  { location: 'FL - Miami North', port: 'NJ',	value: 750 },
  { location: 'FL - Miami South', port: 'NJ',	value: 700 },
  { location: 'FL - Ocala', port: 'NJ',	value: 850 },
  { location: 'FL - Punta Gorda', port: 'NJ',	value: 850 },
  { location: 'FL - Tallahassee', port: 'NJ',	value: 1000 },
  { location: 'FL - Tampa South', port: 'NJ',	value: 825 },
  { location: 'FL - West Palm Beach', port: 'NJ',	value: 825 },
  { location: 'GA - Atlanta East', port: 'NJ',	value: 825 },
  { location: 'GA - Atlanta North', port: 'NJ',	value: 725 },
  { location: 'GA - Atlanta South', port: 'NJ',	value: 725 },
  { location: 'GA - Atlanta West', port: 'NJ',	value: 725 },
  { location: 'GA - Cartersville', port: 'NJ',	value: 700 },
  { location: 'GA - CrashedToys Atlanta', port: 'NJ',	value: 700 },
  { location: 'GA - Macon', port: 'NJ',	value: 875 },
  { location: 'GA - Savannah', port: 'NJ',	value: 850 },
  { location: 'GA - Tifton', port: 'NJ',	value: 850 },
  { location: 'HI - Honolulu', port: 'NJ',	value: 2900 },
  { location: 'IA - Davenport', port: 'NJ',	value: 725 },
  { location: 'IA - Des Moines', port: 'NJ',	value: 725 },
  { location: 'ID - Boise', port: 'NJ',	value: 1750 },
  { location: 'IL - Chicago North', port: 'NJ',	value: 625 },
  { location: 'IL - Chicago South', port: 'NJ',	value: 600 },
  { location: 'IL - Peoria', port: 'NJ',	value: 625 },
  { location: 'IL - Southern Illinois', port: 'NJ',	value: 625 },
  { location: 'IL - Wheeling', port: 'NJ',	value: 625 },
  { location: 'IN - Fort Wayne', port: 'NJ',	value: 700 },
  { location: 'IN - Hammond', port: 'NJ',	value: 625 },
  { location: 'IN - Indianapolis', port: 'NJ',	value: 600 },
  { location: 'IN - Cicero', port: 'NJ',	value: 725 },
  { location: 'IN - DYER', port: 'NJ',	value: 750 },
  { location: 'KS - Kansas City', port: 'NJ',	value: 650 },
  { location: 'KS - Wichita', port: 'NJ',	value: 800 },
  { location: 'KY - Lexington East', port: 'NJ',	value: 775 },
  { location: 'KY - Lexington West', port: 'NJ',	value: 800 },
  { location: 'KY - LOUISVILLE', port: 'NJ',	value: 650 },
  { location: 'KY - Walton', port: 'NJ',	value: 625 },
  { location: 'LA - Baton Rouge', port: 'NJ',	value: 900 },
  { location: 'LA - New Orleans', port: 'NJ',	value: 1150 },
  { location: 'LA - Shreveport', port: 'NJ',	value: 1100 },
  { location: 'MA - North Boston', port: 'NJ',	value: 400 },
  { location: 'MA - South Boston', port: 'NJ',	value: 400 },
  { location: 'MA - West Warren', port: 'NJ',	value: 400 },
  { location: 'MD - Baltimore', port: 'NJ',	value: 375 },
  { location: 'MD - Baltimore East', port: 'NJ',	value: 400 },
  { location: 'DC - Washington DC', port: 'NJ',	value: 400 },
  { location: 'ME - Lyman', port: 'NJ',	value: 525 },
  { location: 'MI - Detroit', port: 'NJ',	value: 550 },
  { location: 'MI - Flint', port: 'NJ',	value: 675 },
  { location: 'MI - Ionia', port: 'NJ',	value: 675 },
  { location: 'MI - Kincheloe', port: 'NJ',	value: 975 },
  { location: 'MI - Lansing', port: 'NJ',	value: 750 },
  { location: 'MN - CrashedToys Minneapolis', port: 'NJ',	value: 650 },
  { location: 'MN - Minneapolis', port: 'NJ',	value: 650 },
  { location: 'MN - Minneapolis North', port: 'NJ',	value: 650 },
  { location: 'MN - St. Cloud', port: 'NJ',	value: 750 },
  { location: 'MO - Springfield', port: 'NJ',	value: 675 },
  { location: 'MO - Columbia', port: 'NJ',	value: 750 },
  { location: 'MO - Sikeston', port: 'NJ',	value: 800 },
  { location: 'MO - St. Louis', port: 'NJ',	value: 575 },
  { location: 'MS - Jackson', port: 'NJ',	value: 1050 },
  { location: 'MT - Billings', port: 'NJ',	value: 1650 },
  { location: 'MT - Helena', port: 'NJ',	value: 1850 },
  { location: 'NC - China Grove', port: 'NJ',	value: 550 },
  { location: 'NC - Lumberton', port: 'NJ',	value: 775 },
  { location: 'NC - Mebane', port: 'NJ',	value: 700 },
  { location: 'NC - Mocksville', port: 'NJ',	value: 675 },
  { location: 'NC - Raleigh', port: 'NJ',	value: 625 },
  { location: 'NC - RALEIGH NORTH', port: 'NJ',	value: 725 },
  { location: 'NC - Concord', port: 'NJ',	value: 575 },
  { location: 'NC - GASTONIA', port: 'NJ',	value: 825 },
  { location: 'ND - BISMARCK', port: 'NJ',	value: 1450 },
  { location: 'NE - Lincoln', port: 'NJ',	value: 750 },
  { location: 'NH - Candia', port: 'NJ',	value: 450 },
  { location: 'NJ - Glassboro East', port: 'NJ',	value: 300 },
  { location: 'NJ - Somerville', port: 'NJ',	value: 275 },
  { location: 'NJ - Trenton', port: 'NJ',	value: 250 },
  { location: 'NJ - Glassboro West', port: 'NJ',	value: 300 },
  { location: 'NM - Albuquerque', port: 'NJ',	value: 1500 },
  { location: 'NV - Las Vegas', port: 'NJ',	value: 1550 },
  { location: 'NV - Reno', port: 'NJ',	value: 1700 },
  { location: 'NY - Albany', port: 'NJ',	value: 375 },
  { location: 'NY - Buffalo', port: 'NJ',	value: 550 },
  { location: 'NY - Long Island', port: 'NJ',	value: 325 },
  { location: 'NY - Newburgh', port: 'NJ',	value: 325 },
  { location: 'NY - Rochester', port: 'NJ',	value: 475 },
  { location: 'NY - Syracuse', port: 'NJ',	value: 450 },
  { location: 'OH - Cleveland East', port: 'NJ',	value: 525 },
  { location: 'OH - Cleveland West', port: 'NJ',	value: 525 },
  { location: 'OH - Columbus', port: 'NJ',	value: 650 },
  { location: 'OH - Dayton', port: 'NJ',	value: 550 },
  { location: 'OK - Oklahoma City', port: 'NJ',	value: 1000 },
  { location: 'OK - Tulsa', port: 'NJ',	value: 1075 },
  { location: 'OR - Eugene', port: 'NJ',	value: 1850 },
  { location: 'OR - Portland North', port: 'NJ',	value: 1950 },
  { location: 'OR - Portland South', port: 'NJ',	value: 1850 },
  { location: 'PA - Altoona', port: 'NJ',	value: 500 },
  { location: 'PA - Chambersburg', port: 'NJ',	value: 450 },
  { location: 'PA - Harrisburg', port: 'NJ',	value: 375 },
  { location: 'PA - Philadelphia', port: 'NJ',	value: 300 },
  { location: 'PA - Philadelphia East', port: 'NJ',	value: 325 },
  { location: 'PA - Pittsburgh East', port: 'NJ',	value: 450 },
  { location: 'PA - Pittsburgh West', port: 'NJ',	value: 500 },
  { location: 'PA - Pittsburgh North', port: 'NJ',	value: 500 },
  { location: 'PA - Pittsburgh South', port: 'NJ',	value: 500 },
  { location: 'PA - Scranton', port: 'NJ',	value: 350 },
  { location: 'PA - York Haven', port: 'NJ',	value: 375 },
  { location: 'RI - Exeter', port: 'NJ',	value: 400 },
  { location: 'SC - Columbia', port: 'NJ',	value: 725 },
  { location: 'SC - North Charleston', port: 'NJ',	value: 800 },
  { location: 'SC - Spartanburg', port: 'NJ',	value: 700 },
  { location: 'TN - Knoxville', port: 'NJ',	value: 800 },
  { location: 'TN - Memphis', port: 'NJ',	value: 825 },
  { location: 'TN - Nashville', port: 'NJ',	value: 800 },
  { location: 'TX - Abilene', port: 'NJ',	value: 1350 },
  { location: 'TX - Amarillo', port: 'NJ',	value: 1600 },
  { location: 'TX - Andrews', port: 'NJ',	value: 1550 },
  { location: 'TX - Austin', port: 'NJ',	value: 1100 },
  { location: 'TX - Corpus Christi', port: 'NJ',	value: 1300 },
  { location: 'TX - CrashedToys Dallas', port: 'NJ',	value: 850 },
  { location: 'TX - Dallas', port: 'NJ',	value: 900 },
  { location: 'TX - Dallas South', port: 'NJ',	value: 850 },
  { location: 'TX - El Paso', port: 'NJ',	value: 1375 },
  { location: 'TX - Ft. Worth', port: 'NJ',	value: 1025 },
  { location: 'TX - Houston', port: 'NJ',	value: 900 },
  { location: 'TX - Houston East', port: 'NJ',	value: 925 },
  { location: 'TX - Longview', port: 'NJ',	value: 1000 },
  { location: 'TX - Lufkin', port: 'NJ',	value: 1050 },
  { location: 'TX - McAllen', port: 'NJ',	value: 1600 },
  { location: 'TX - San Antonio', port: 'NJ',	value: 1200 },
  { location: 'TX - Waco', port: 'NJ',	value: 1150 },
  { location: 'UT - Ogden', port: 'NJ',	value: 1775 },
  { location: 'UT - Salt Lake City', port: 'NJ',	value: 1650 },
  { location: 'VA - Danville', port: 'NJ',	value: 575 },
  { location: 'VA - Fredericksburg', port: 'NJ',	value: 400 },
  { location: 'VA - Hampton', port: 'NJ',	value: 450 },
  { location: 'VA - Richmond', port: 'NJ',	value: 450 },
  { location: 'VA - Richmond East', port: 'NJ',	value: 425 },
  { location: 'WA - Graham', port: 'NJ',	value: 1750 },
  { location: 'WA - North Seattle', port: 'NJ',	value: 1750 },
  { location: 'WA - Pasco', port: 'NJ',	value: 1850 },
  { location: 'WA - Spokane', port: 'NJ',	value: 1850 },
  { location: 'WI - Appleton', port: 'NJ',	value: 675 },
  { location: 'WI - Madison', port: 'NJ',	value: 700 },
  { location: 'WI - Milwaukee North', port: 'NJ',	value: 775 },
  { location: 'WI - Milwaukee', port: 'NJ',	value: 700 },
  { location: 'WV - Charleston', port: 'NJ',	value: 600 },
  { location: 'WY - Casper', port: 'NJ',	value: 1650 },
  { location: 'AL - Birmingham', port: 'GA',	value: 450},
  { location: 'AL - Mobile', port: 'GA',	value: 500},
  { location: 'AL - Montgomery', port: 'GA',	value: 450},
  { location: 'AL - Tanner', port: 'GA',	value: 475},
  { location: 'AL - Dothan', port: 'GA',	value: 450},
  { location: 'AR - Little Rock', port: 'GA',	value: 550},
  { location: 'FL - Jacksonville East', port: 'GA',	value: 275},
  { location: 'FL - Jacksonville West', port: 'GA',	value: 275},
  { location: 'FL - Jacksonville North', port: 'GA',	value: 300},
  { location: 'FL - Orlando North', port: 'GA',	value: 350},
  { location: 'FL - Orlando South', port: 'GA',	value: 375},
  { location: 'FL - Ft. Pierce', port: 'GA',	value: 450},
  { location: 'FL - Miami Central', port: 'GA',	value: 375},
  { location: 'FL - Miami North', port: 'GA',	value: 375},
  { location: 'FL - Miami South', port: 'GA',	value: 375},
  { location: 'FL - Ocala', port: 'GA',	value: 450},
  { location: 'FL - Punta Gorda', port: 'GA',	value: 450},
  { location: 'FL - Tallahassee', port: 'GA',	value: 450},
  { location: 'FL - Tampa South', port: 'GA',	value: 350},
  { location: 'FL - West Palm Beach', port: 'GA',	value: 400},
  { location: 'GA - Atlanta East', port: 'GA',	value: 350},
  { location: 'GA - Atlanta North', port: 'GA',	value: 375},
  { location: 'GA - Atlanta South', port: 'GA',	value: 375},
  { location: 'GA - Atlanta West', port: 'GA',	value: 375},
  { location: 'GA - Cartersville', port: 'GA',	value: 375},
  { location: 'GA - CrashedToys Atlanta', port: 'GA',	value: 300},
  { location: 'GA - Macon', port: 'GA',	value: 350},
  { location: 'GA - Savannah', port: 'GA',	value: 200},
  { location: 'GA - Tifton', port: 'GA',	value: 350},
  { location: 'KY - Lexington East', port: 'GA',	value: 650},
  { location: 'KY - Lexington West', port: 'GA',	value: 625},
  { location: 'KY - LOUISVILLE', port: 'GA',	value: 575},
  { location: 'LA - New Orleans', port: 'GA',	value: 550},
  { location: 'MO - Springfield', port: 'GA',	value: 675},
  { location: 'MS - Jackson', port: 'GA',	value: 550},
  { location: 'NC - China Grove', port: 'GA',	value: 400},
  { location: 'NC - Lumberton', port: 'GA',	value: 400},
  { location: 'NC - Mebane', port: 'GA',	value: 500},
  { location: 'NC - Mocksville', port: 'GA',	value: 450},
  { location: 'NC - Raleigh', port: 'GA',	value: 375},
  { location: 'NC - RALEIGH NORTH', port: 'GA',	value: 300},
  { location: 'NC - Concord', port: 'GA',	value: 400},
  { location: 'NC - GASTONIA', port: 'GA',	value: 500},
  { location: 'SC - Columbia', port: 'GA',	value: 300},
  { location: 'SC - North Charleston', port: 'GA',	value: 300},
  { location: 'SC - Spartanburg', port: 'GA',	value: 375},
  { location: 'TN - Knoxville', port: 'GA',	value: 450},
  { location: 'TN - Memphis', port: 'GA',	value: 550},
  { location: 'TN - Nashville', port: 'GA',	value: 500},
  { location: 'VA - Danville', port: 'GA',	value: 525},
  { location: 'AL - Birmingham', port: 'TX', value:	775 },
  { location: 'AR - Fayetteville', port: 'TX', value:	550 },
  { location: 'AR - Little Rock', port: 'TX', value:	450 },
  { location: 'AZ - Phoenix', port: 'TX', value:	1250 },
  { location: 'AZ - Tucson', port: 'TX', value:	1350 },
  { location: 'CA - Antelope', port: 'TX', value:	1550 },
  { location: 'CA - Fresno', port: 'TX', value:	1550 },
  { location: 'CA - Hayward', port: 'TX', value:	1600 },
  { location: 'CA - Long Beach', port: 'TX', value:	1500 },
  { location: 'CA - Los Angeles', port: 'TX', value:	1450 },
  { location: 'CA - Martinez', port: 'TX', value:	1700 },
  { location: 'CA - Rancho Cucamonga', port: 'TX', value:	1600 },
  { location: 'CA - Sacramento', port: 'TX', value:	1700 },
  { location: 'CA - San Bernardino', port: 'TX', value:	1450 },
  { location: 'CA - San Diego', port: 'TX', value:	1350 },
  { location: 'CA - San Jose', port: 'TX', value:	1650 },
  { location: 'CA - So Sacramento', port: 'TX', value:	1600 },
  { location: 'CA - Sun Valley', port: 'TX', value:	1450 },
  { location: 'CA - Vallejo', port: 'TX', value:	1700 },
  { location: 'CA - Van Nuys', port: 'TX', value:	1500 },
  { location: 'CA - Redding', port: 'TX', value:	1750 },
  { location: 'CO - Colorado Springs', port: 'TX', value:	925 },
  { location: 'CO - Denver', port: 'TX', value:	750 },
  { location: 'CO - Denver Central', port: 'TX', value:	675 },
  { location: 'CO - Denver South', port: 'TX', value:	700 },
  { location: 'GA - Atlanta South', port: 'TX', value:	775 },
  { location: 'GA - Atlanta West', port: 'TX', value:	775 },
  { location: 'GA - Macon', port: 'TX', value:	775 },
  { location: 'ID - Boise', port: 'TX', value:	1750 },
  { location: 'KS - Wichita', port: 'TX', value:	700 },
  { location: 'LA - Baton Rouge', port: 'TX', value:	450 },
  { location: 'LA - New Orleans', port: 'TX', value:	450 },
  { location: 'LA - Shreveport', port: 'TX', value:	325 },
  { location: 'NC - Mebane', port: 'TX', value:	925 },
  { location: 'ND - BISMARCK', port: 'TX', value:	1250 },
  { location: 'NM - Albuquerque', port: 'TX', value:	650 },
  { location: 'NV - Las Vegas', port: 'TX', value:	1100 },
  { location: 'NV - Reno', port: 'TX', value:	1500 },
  { location: 'OK - Oklahoma City', port: 'TX', value:	500 },
  { location: 'OK - Tulsa', port: 'TX', value:	500 },
  { location: 'OR - Eugene', port: 'TX', value:	1750 },
  { location: 'OR - Portland North', port: 'TX', value:	1750 },
  { location: 'TN - Knoxville', port: 'TX', value:	850 },
  { location: 'TX - Abilene', port: 'TX', value:	450 },
  { location: 'TX - Amarillo', port: 'TX', value:	500 },
  { location: 'TX - Andrews', port: 'TX', value:	525 },
  { location: 'TX - Austin', port: 'TX', value:	325 },
  { location: 'TX - Corpus Christi', port: 'TX', value:	375 },
  { location: 'TX - CrashedToys Dallas', port: 'TX', value:	325 },
  { location: 'TX - Dallas', port: 'TX', value:	325 },
  { location: 'TX - Dallas South', port: 'TX', value:	350 },
  { location: 'TX - El Paso', port: 'TX', value:	525 },
  { location: 'TX - Ft. Worth', port: 'TX', value:	325 },
  { location: 'TX - Houston', port: 'TX', value:	300 },
  { location: 'TX - Houston East', port: 'TX', value:	300 },
  { location: 'TX - Longview', port: 'TX', value:	350 },
  { location: 'TX - Lufkin', port: 'TX', value:	350 },
  { location: 'TX - McAllen', port: 'TX', value:	400 },
  { location: 'TX - San Antonio', port: 'TX', value:	350 },
  { location: 'TX - Waco', port: 'TX', value:	400 },
  { location: 'UT - Ogden', port: 'TX', value:	1350 },
  { location: 'UT - Salt Lake City', port: 'TX', value:	1350 },
  { location: 'WA - North Seattle', port: 'TX', value:	1675 },
  { location: 'AK - Anchorage', port: 'CA', value:	2100 },
  { location: 'AZ - Phoenix', port: 'CA', value:	375 },
  { location: 'AZ - Tucson', port: 'CA', value:	500 },
  { location: 'CA - Antelope', port: 'CA', value:	425 },
  { location: 'CA - Bakersfield', port: 'CA', value:	375 },
  { location: 'CA - Crashedtoys Sacramento', port: 'CA', value:	450 },
  { location: 'CA - Fresno', port: 'CA', value:	375 },
  { location: 'CA - Hayward', port: 'CA', value:	475 },
  { location: 'CA - Long Beach', port: 'CA', value:	275 },
  { location: 'CA - Los Angeles', port: 'CA', value:	250 },
  { location: 'CA - Martinez', port: 'CA', value:	475 },
  { location: 'CA - Rancho Cucamonga', port: 'CA', value:	250 },
  { location: 'CA - Sacramento', port: 'CA', value:	475 },
  { location: 'CA - San Bernardino', port: 'CA', value:	300 },
  { location: 'CA - San Diego', port: 'CA', value:	350 },
  { location: 'CA - San Jose', port: 'CA', value:	450 },
  { location: 'CA - So Sacramento', port: 'CA', value:	450 },
  { location: 'CA - Sun Valley', port: 'CA', value:	275 },
  { location: 'CA - Vallejo', port: 'CA', value:	475 },
  { location: 'CA - Van Nuys', port: 'CA', value:	275 },
  { location: 'CA - Redding', port: 'CA', value:	525 },
  { location: 'CO - Colorado Springs', port: 'CA', value:	750 },
  { location: 'HI - Honolulu', port: 'CA', value:	1700 },
  { location: 'ID - Boise', port: 'CA', value:	700 },
  { location: 'MT - Billings', port: 'CA', value:	1200 },
  { location: 'MT - Helena', port: 'CA', value:	1100 },
  { location: 'NV - Las Vegas', port: 'CA', value:	550 },
  { location: 'NV - Reno', port: 'CA', value:	675 },
  { location: 'OR - Eugene', port: 'CA', value:	725 },
  { location: 'OR - Portland North', port: 'CA', value:	700 },
  { location: 'OR - Portland South', port: 'CA', value:	675 },
  { location: 'UT - Ogden', port: 'CA', value:	500 },
  { location: 'UT - Salt Lake City', port: 'CA', value:	600 },
  { location: 'WA - Graham', port: 'CA', value:	700 },
  { location: 'WA - North Seattle', port: 'CA', value:	700 },
  { location: 'WA - Pasco', port: 'CA', value:	1150 },
  { location: 'WA - Spokane', port: 'CA', value:	925 },
  { location: 'WY - Casper', port: 'CA', value:	950 }
];

export const iaai = [
{ location: 'AL - Birmingham ADESA', port: 'NJ', value:	850 },
{ location: 'AL - Birmingham', port: 'NJ', value:	850 },
{ location: 'AL - Dothan', port: 'NJ', value:	850 },
{ location: 'AL - Huntsville', port: 'NJ', value:	800 },
{ location: 'AR - Fayetteville', port: 'NJ', value:	1200 },
{ location: 'AR - Little Rock', port: 'NJ', value:	950 },
{ location: 'AZ - Phoenix', port: 'NJ', value:	1575 },
{ location: 'AZ - Tucson', port: 'NJ', value:	1600 },
{ location: 'CA - ACE - Carson', port: 'NJ', value:	1650 },
{ location: 'CA - ACE - Perris', port: 'NJ', value:	1650 },
{ location: 'CA - Anaheim', port: 'NJ', value:	1675 },
{ location: 'CA - Colton', port: 'NJ', value:	1675 },
{ location: 'CA - East Bay', port: 'NJ', value:	1675 },
{ location: 'CA - Fontana', port: 'NJ', value:	1600 },
{ location: 'CA - Fremont', port: 'NJ', value:	1675 },
{ location: 'CA - Fresno', port: 'NJ', value:	1700 },
{ location: 'CA - High Desert', port: 'NJ', value:	1750 },
{ location: 'CA - Los Angeles', port: 'NJ', value:	1575 },
{ location: 'CA - Los Angeles', port: 'NJ', value:	1550 },
{ location: 'CA - North Hollywood', port: 'NJ', value:	1650 },
{ location: 'CA - Sacramento', port: 'NJ', value:	1750 },
{ location: 'CA - San Diego', port: 'NJ', value:	1750 },
{ location: 'CO - Denver', port: 'NJ', value:	950 },
{ location: 'CO - Denver East', port: 'NJ', value:	750 },
{ location: 'CO - Western Colorado', port: 'NJ', value:	1350 },
{ location: 'CO - Colorado Springs', port: 'NJ', value:	1100 },
{ location: 'CT - Hartford', port: 'NJ', value:	350 },
{ location: 'CT - Hartford - South', port: 'NJ', value:	350 },
{ location: 'DE - New Castle', port: 'NJ', value:	350 },
{ location: 'FL - Clearwater', port: 'NJ', value:	1000 },
{ location: 'FL - Jacksonville', port: 'NJ', value:	750 },
{ location: 'FL - Pensacola', port: 'NJ', value:	950 },
{ location: 'FL - Orlando', port: 'NJ', value:	975 },
{ location: 'FL - Orlando North', port: 'NJ', value:	750 },
{ location: 'FL - Fort Myers', port: 'NJ', value:	950 },
{ location: 'FL - Fort Pierce', port: 'NJ', value:	750 },
{ location: 'FL - Miami', port: 'NJ', value:	650 },
{ location: 'FL - Miami - North', port: 'NJ', value:	750 },
{ location: 'FL - Tampa', port: 'NJ', value:	650 },
{ location: 'FL - Tampa North', port: 'NJ', value:	750 },
{ location: 'GA - Atlanta', port: 'NJ', value:	650 },
{ location: 'GA - Atlanta East', port: 'NJ', value:	650 },
{ location: 'GA - Atlanta North', port: 'NJ', value:	650 },
{ location: 'GA - Atlanta South', port: 'NJ', value:	650 },
{ location: 'GA - Macon', port: 'NJ', value:	800 },
{ location: 'GA - Savannah', port: 'NJ', value:	750 },
{ location: 'GA - Tifton', port: 'NJ', value:	750 },
{ location: 'HI - Honolulu', port: 'NJ', value:	2700 },
{ location: 'IA - Davenport', port: 'NJ', value:	650 },
{ location: 'IA - Des Moines', port: 'NJ', value:	675 },
{ location: 'ID - Boise', port: 'NJ', value:	1650 },
{ location: 'IL - Chicago - North', port: 'NJ', value:	650 },
{ location: 'IL - Chicago - South', port: 'NJ', value:	650 },
{ location: 'IL - Chicago - West', port: 'NJ', value:	600 },
{ location: 'IL - Lincoln', port: 'NJ', value:	675 },
{ location: 'IL - Specialty Division', port: 'NJ', value:	625 },
{ location: 'IL - St. Louis', port: 'NJ', value:	650 },
{ location: 'IN - Indianapolis', port: 'NJ', value:	600 },
{ location: 'IN - South Bend', port: 'NJ', value:	650 },
{ location: 'KS - Kansas City', port: 'NJ', value:	600 },
{ location: 'KS - Wichita', port: 'NJ', value:	950 },
{ location: 'KY - Ashland', port: 'NJ', value:	600 },
{ location: 'KY - Bowling Green', port: 'NJ', value:	750 },
{ location: 'KY - Louisville', port: 'NJ', value:	700 },
{ location: 'KY - Louisville North', port: 'NJ', value:	800 },
{ location: 'KY - Paducah', port: 'NJ', value:	950 },
{ location: 'LA - Lafayette', port: 'NJ', value:	950 },
{ location: 'LA - Shreveport', port: 'NJ', value:	950 },
{ location: 'LA - Baton Rouge', port: 'NJ', value:	1100 },
{ location: 'LA - New Orleans', port: 'NJ', value:	1100 },
{ location: 'LA - New Orleans East', port: 'NJ', value:	975 },
{ location: 'MA - Boston - Shirley', port: 'NJ', value:	450 },
{ location: 'MA - Taunton', port: 'NJ', value:	375 },
{ location: 'MA - Templeton', port: 'NJ', value:	450 },
{ location: 'MD - Baltimore', port: 'NJ', value:	400 },
{ location: 'MD - Dundalk', port: 'NJ', value:	375 },
{ location: 'MD - Laurel', port: 'NJ', value:	375 },
{ location: 'MD - Metro DC', port: 'NJ', value:	375 },
{ location: 'ME - Portland - Gorham', port: 'NJ', value:	550 },
{ location: 'MI - Detroit', port: 'NJ', value:	550 },
{ location: 'MI - Flint', port: 'NJ', value:	650 },
{ location: 'MI - Grand Rapids', port: 'NJ', value:	700 },
{ location: 'MN - Minneapolis/St. Paul', port: 'NJ', value:	700 },
{ location: 'MO - Springfield', port: 'NJ', value:	700 },
{ location: 'MO - Odessa', port: 'NJ', value:	950 },
{ location: 'MS - Grenada', port: 'NJ', value:	1100 },
{ location: 'MS - Gulf Coast', port: 'NJ', value:	1100 },
{ location: 'MS - Jackson', port: 'NJ', value:	1100 },
{ location: 'MT - Billings', port: 'NJ', value:	1700 },
{ location: 'MT - Missoula', port: 'NJ', value:	1800 },
{ location: 'NC - Asheville', port: 'NJ', value:	675 },
{ location: 'NC - Charlotte', port: 'NJ', value:	725 },
{ location: 'NC - Concord', port: 'NJ', value:	625 },
{ location: 'NC - Greensboro', port: 'NJ', value:	675 },
{ location: 'NC - Raleigh', port: 'NJ', value:	650 },
{ location: 'NC - Wilmington', port: 'NJ', value:	775 },
{ location: 'ND - Fargo', port: 'NJ', value:	1000 },
{ location: 'NE - Omaha', port: 'NJ', value:	775 },
{ location: 'NH - Manchester', port: 'NJ', value:	475 },
{ location: 'NJ - Avenel New Jersey', port: 'NJ', value:	250 },
{ location: 'NJ - Central New Jersey', port: 'NJ', value:	250 },
{ location: 'NJ - Northern New Jersey', port: 'NJ', value:	250 },
{ location: 'NJ - Southern New Jersey', port: 'NJ', value:	275 },
{ location: 'NJ - Englishtown', port: 'NJ', value:	325 },
{ location: 'NJ - Sayreville', port: 'NJ', value:	325 },
{ location: 'NM - Albuquerque', port: 'NJ', value:	1550 },
{ location: 'NV - Las Vegas', port: 'NJ', value:	1450 },
{ location: 'NV - Reno', port: 'NJ', value:	1600 },
{ location: 'NY - Albany', port: 'NJ', value:	375 },
{ location: 'NY - Buffalo', port: 'NJ', value:	525 },
{ location: 'NY - Long Island', port: 'NJ', value:	350 },
{ location: 'NY - Newburgh', port: 'NJ', value:	300 },
{ location: 'NY - Rochester', port: 'NJ', value:	500 },
{ location: 'NY - Syracuse', port: 'NJ', value:	425 },
{ location: 'OH - Akron - Canton', port: 'NJ', value:	525 },
{ location: 'OH - Cincinnati', port: 'NJ', value:	600 },
{ location: 'OH - Cincinnati - South', port: 'NJ', value:	550 },
{ location: 'OH - Cleveland', port: 'NJ', value:	500 },
{ location: 'OH - Columbus', port: 'NJ', value:	650 },
{ location: 'OH - Dayton', port: 'NJ', value:	550 },
{ location: 'OK - Oklahoma City', port: 'NJ', value:	1100 },
{ location: 'OK - Tulsa', port: 'NJ', value:	900 },
{ location: 'OR - Eugene', port: 'NJ', value:	1750 },
{ location: 'OR - Portland', port: 'NJ', value:	1650 },
{ location: 'OR - Portland West', port: 'NJ', value:	1650 },
{ location: 'PA - Altoona', port: 'NJ', value:	500 },
{ location: 'PA - Bridgeport', port: 'NJ', value:	325 },
{ location: 'PA - Erie', port: 'NJ', value:	575 },
{ location: 'PA - Philadelphia', port: 'NJ', value:	300 },
{ location: 'PA - Pittsburgh', port: 'NJ', value:	525 },
{ location: 'PA - Pittsburgh - North', port: 'NJ', value:	525 },
{ location: 'PA - Scranton', port: 'NJ', value:	350 },
{ location: 'PA - York Springs', port: 'NJ', value:	375 },
{ location: 'RI - Providence', port: 'NJ', value:	425 },
{ location: 'SC - Charleston', port: 'NJ', value:	700 },
{ location: 'SC - Columbia', port: 'NJ', value:	725 },
{ location: 'SC - Greenville', port: 'NJ', value:	750 },
{ location: 'SC - Lexington', port: 'NJ', value:	750 },
{ location: 'SD - Sioux Falls', port: 'NJ', value:	925 },
{ location: 'TN - Chattanooga', port: 'NJ', value:	825 },
{ location: 'TN - Knoxville', port: 'NJ', value:	700 },
{ location: 'TN - Memphis', port: 'NJ', value:	825 },
{ location: 'TN - Nashville', port: 'NJ', value:	825 },
{ location: 'TX - Abilene', port: 'NJ', value:	1400 },
{ location: 'TX - Amarillo', port: 'NJ', value:	1400 },
{ location: 'TX - Austin', port: 'NJ', value:	1100 },
{ location: 'TX - Corpus Christi', port: 'NJ', value:	1200 },
{ location: 'TX - Dallas', port: 'NJ', value:	875 },
{ location: 'TX - IAA Dallas/Ft Worth', port: 'NJ', value:	850 },
{ location: 'TX - El Paso', port: 'NJ', value:	1350 },
{ location: 'TX - Fort Worth North', port: 'NJ', value:	1000 },
{ location: 'TX - Houston', port: 'NJ', value:	950 },
{ location: 'TX - Houston South', port: 'NJ', value:	1025 },
{ location: 'TX - Houston - North', port: 'NJ', value:	950 },
{ location: 'TX - Longview', port: 'NJ', value:	1000 },
{ location: 'TX - Lubbock', port: 'NJ', value:	1400 },
{ location: 'TX - McAllen', port: 'NJ', value:	1450 },
{ location: 'TX - Permian Basin', port: 'NJ', value:	1400 },
{ location: 'TX - San Antonio', port: 'NJ', value:	1175 },
{ location: 'TX - San Antonio - South', port: 'NJ', value:	1250 },
{ location: 'UT - Salt Lake City', port: 'NJ', value:	1650 },
{ location: 'VA - Culpeper', port: 'NJ', value:	450 },
{ location: 'VA - Fredericksburg - South', port: 'NJ', value:	400 },
{ location: 'VA - Northern Virginia', port: 'NJ', value:	400 },
{ location: 'VA - Pulaski', port: 'NJ', value:	475 },
{ location: 'VA - Richmond', port: 'NJ', value:	425 },
{ location: 'VA - Roanoke', port: 'NJ', value:	500 },
{ location: 'VA - Suffolk', port: 'NJ', value:	500 },
{ location: 'VA - Tidewater', port: 'NJ', value:	475 },
{ location: 'VT - Burlington', port: 'NJ', value:	575 },
{ location: 'WA - Seattle', port: 'NJ', value:	1750 },
{ location: 'WA - Spokane', port: 'NJ', value:	1950 },
{ location: 'WI - Appleton', port: 'NJ', value:	700 },
{ location: 'WI - Milwaukee', port: 'NJ', value:	700 },
{ location: 'WI - Portage', port: 'NJ', value:	650 },
{ location: 'WV - Buckhannon', port: 'NJ', value:	600 },
{ location: 'WV - Shady Spring', port: 'NJ', value:	625 },
{ location: 'WY - Casper', port: 'NJ', value:	1575 },
{ location: 'AL - Birmingham ADESA', port: 'GA', value:	450 },
{ location: 'AL - Birmingham', port: 'GA', value:	450 },
{ location: 'AL - Dothan', port: 'GA', value:	450 },
{ location: 'AL - Huntsville', port: 'GA', value:	475 },
{ location: 'AR - Little Rock', port: 'GA', value:	550 },
{ location: 'FL - Clearwater', port: 'GA', value:	375 },
{ location: 'FL - Jacksonville', port: 'GA', value:	250 },
{ location: 'FL - Pensacola', port: 'GA', value:	500 },
{ location: 'FL - Orlando', port: 'GA', value:	275 },
{ location: 'FL - Orlando North', port: 'GA', value:	350 },
{ location: 'FL - Fort Myers', port: 'GA', value:	450 },
{ location: 'FL - Fort Pierce', port: 'GA', value:	450 },
{ location: 'FL - Miami', port: 'GA', value:	375 },
{ location: 'FL - Miami - North', port: 'GA', value:	450 },
{ location: 'FL - Tampa', port: 'GA', value:	450 },
{ location: 'FL - Tampa North', port: 'GA', value:	475 },
{ location: 'GA - Atlanta', port: 'GA', value:	350 },
{ location: 'GA - Atlanta East', port: 'GA', value:	350 },
{ location: 'GA - Atlanta North', port: 'GA', value:	350 },
{ location: 'GA - Atlanta South', port: 'GA', value:	350 },
{ location: 'GA - Macon', port: 'GA', value:	325 },
{ location: 'GA - Savannah', port: 'GA', value:	225 },
{ location: 'GA - Tifton', port: 'GA', value:	350 },
{ location: 'KY - Bowling Green', port: 'GA', value:	650 },
{ location: 'KY - Louisville', port: 'GA', value:	550 },
{ location: 'KY - Louisville North', port: 'GA', value:	725 },
{ location: 'KY - Paducah', port: 'GA', value:	575 },
{ location: 'LA - Baton Rouge', port: 'GA', value:	500 },
{ location: 'LA - New Orleans', port: 'GA', value:	425 },
{ location: 'LA - New Orleans East', port: 'GA', value:	500 },
{ location: 'MO - Springfield', port: 'GA', value:	700 },
{ location: 'MS - Grenada', port: 'GA', value:	550 },
{ location: 'MS - Gulf Coast', port: 'GA', value:	500 },
{ location: 'MS - Jackson', port: 'GA', value:	500 },
{ location: 'NC - Asheville', port: 'GA', value:	450 },
{ location: 'NC - Charlotte', port: 'GA', value:	375 },
{ location: 'NC - Concord', port: 'GA', value:	400 },
{ location: 'NC - Greensboro', port: 'GA', value:	425 },
{ location: 'NC - Raleigh', port: 'GA', value:	400 },
{ location: 'NC - Wilmington', port: 'GA', value:	400 },
{ location: 'ND - Fargo', port: 'GA', value:	1000 },
{ location: 'SC - Charleston', port: 'GA', value:	325 },
{ location: 'SC - Columbia', port: 'GA', value:	300 },
{ location: 'SC - Greenville', port: 'GA', value:	375 },
{ location: 'SC - Lexington', port: 'GA', value:	325 },
{ location: 'TN - Chattanooga', port: 'GA', value:	500 },
{ location: 'TN - Knoxville', port: 'GA', value:	475 },
{ location: 'TN - Memphis', port: 'GA', value:	525 },
{ location: 'TN - Nashville', port: 'GA', value:	450 },
{ location: 'AR - Fayetteville', port: 'TX', value:	500 },
{ location: 'AR - Little Rock', port: 'TX', value:	450 },
{ location: 'AZ - Phoenix', port: 'TX', value:	1000 },
{ location: 'AZ - Tucson', port: 'TX', value:	1100 },
{ location: 'CA - ACE - Carson', port: 'TX', value:	1500 },
{ location: 'CA - ACE - Perris', port: 'TX', value:	1550 },
{ location: 'CA - Anaheim', port: 'TX', value:	1450 },
{ location: 'CA - Colton', port: 'TX', value:	1450 },
{ location: 'CA - East Bay', port: 'TX', value:	1500 },
{ location: 'CA - Fontana', port: 'TX', value:	1450 },
{ location: 'CA - Fremont', port: 'TX', value:	1450 },
{ location: 'CA - Fresno', port: 'TX', value:	1550 },
{ location: 'CA - High Desert', port: 'TX', value:	1450 },
{ location: 'CA - Los Angeles', port: 'TX', value:	1450 },
{ location: 'CA - Los Angeles', port: 'TX', value:	1450 },
{ location: 'CA - North Hollywood', port: 'TX', value:	1450 },
{ location: 'CA - Sacramento', port: 'TX', value:	1475 },
{ location: 'CA - San Diego', port: 'TX', value:	1550 },
{ location: 'CO - Denver', port: 'TX', value:	700 },
{ location: 'CO - Denver East', port: 'TX', value:	700 },
{ location: 'CO - Western Colorado', port: 'TX', value:	1100 },
{ location: 'CO - Colorado Springs', port: 'TX', value:	850 },
{ location: 'HI - Honolulu', port: 'TX', value:	2700 },
{ location: 'ID - Boise', port: 'TX', value:	1450 },
{ location: 'KS - Wichita', port: 'TX', value:	650 },
{ location: 'LA - Lafayette', port: 'TX', value:	375 },
{ location: 'LA - Shreveport', port: 'TX', value:	375 },
{ location: 'LA - Baton Rouge', port: 'TX', value:	600 },
{ location: 'LA - New Orleans', port: 'TX', value:	550 },
{ location: 'MO - Odessa', port: 'TX', value:	850 },
{ location: 'MS - Gulf Coast', port: 'TX', value:	550 },
{ location: 'MT - Billings', port: 'TX', value:	1550 },
{ location: 'MT - Missoula', port: 'TX', value:	1550 },
{ location: 'ND - Fargo', port: 'TX', value:	1000 },
{ location: 'NM - Albuquerque', port: 'TX', value:	650 },
{ location: 'NV - Las Vegas', port: 'TX', value:	1200 },
{ location: 'NV - Reno', port: 'TX', value:	1500 },
{ location: 'OK - Oklahoma City', port: 'TX', value:	400 },
{ location: 'OK - Tulsa', port: 'TX', value:	400 },
{ location: 'OR - Eugene', port: 'TX', value:	1550 },
{ location: 'OR - Portland', port: 'TX', value:	1500 },
{ location: 'OR - Portland West', port: 'TX', value:	1500 },
{ location: 'TX - Abilene', port: 'TX', value:	450 },
{ location: 'TX - Amarillo', port: 'TX', value:	525 },
{ location: 'TX - Austin', port: 'TX', value:	325 },
{ location: 'TX - Corpus Christi', port: 'TX', value:	375 },
{ location: 'TX - Dallas', port: 'TX', value:	325 },
{ location: 'TX - IAA Dallas/Ft Worth', port: 'TX', value:	350 },
{ location: 'TX - El Paso', port: 'TX', value:	500 },
{ location: 'TX - Fort Worth North', port: 'TX', value:	400 },
{ location: 'TX - Houston', port: 'TX', value:	275 },
{ location: 'TX - Houston South', port: 'TX', value:	225 },
{ location: 'TX - Houston - North', port: 'TX', value:	225 },
{ location: 'TX - Longview', port: 'TX', value:	375 },
{ location: 'TX - Lubbock', port: 'TX', value:	525 },
{ location: 'TX - McAllen', port: 'TX', value:	375 },
{ location: 'TX - Permian Basin', port: 'TX', value:	550 },
{ location: 'TX - San Antonio', port: 'TX', value:	375 },
{ location: 'TX - San Antonio - South', port: 'TX', value:	350 },
{ location: 'UT - Salt Lake City', port: 'TX', value:	1350 },
{ location: 'WA - Seattle', port: 'TX', value:	1550 },
{ location: 'WA - Spokane', port: 'TX', value:	1750 },
{ location: 'WY - Casper', port: 'TX', value:	1475     },
{ location: 'AK - Anchorage', port: 'CA', value:	2000 },
{ location: 'AZ - Phoenix', port: 'CA', value:	350 },
{ location: 'AZ - Tucson', port: 'CA', value:	375 },
{ location: 'CA - ACE - Carson', port: 'CA', value:	275 },
{ location: 'CA - ACE - Perris', port: 'CA', value:	275 },
{ location: 'CA - Anaheim', port: 'CA', value:	250 },
{ location: 'CA - Colton', port: 'CA', value:	250 },
{ location: 'CA - East Bay', port: 'CA', value:	450 },
{ location: 'CA - Fontana', port: 'CA', value:	250 },
{ location: 'CA - Fremont', port: 'CA', value:	375 },
{ location: 'CA - Fresno', port: 'CA', value:	300 },
{ location: 'CA - High Desert', port: 'CA', value:	250 },
{ location: 'CA - Los Angeles', port: 'CA', value:	175 },
{ location: 'CA - Los Angeles', port: 'CA', value:	225 },
{ location: 'CA - North Hollywood', port: 'CA', value:	225 },
{ location: 'CA - Sacramento', port: 'CA', value:	425 },
{ location: 'CA - San Diego', port: 'CA', value:	250 },
{ location: 'CO - Western Colorado', port: 'CA', value:	900 },
{ location: 'HI - Honolulu', port: 'CA', value:	2200 },
{ location: 'ID - Boise', port: 'CA', value:	750 },
{ location: 'MT - Billings', port: 'CA', value:	1100 },
{ location: 'MT - Missoula', port: 'CA', value:	1100 },
{ location: 'NV - Las Vegas', port: 'CA', value:	400 },
{ location: 'NV - Reno', port: 'CA', value:	700 },
{ location: 'OR - Eugene', port: 'CA', value:	700 },
{ location: 'OR - Portland', port: 'CA', value:	725 },
{ location: 'OR - Portland West', port: 'CA', value:	600 },
{ location: 'UT - Salt Lake City', port: 'CA', value:	550 },
{ location: 'WA - Seattle', port: 'CA', value:	725 },
{ location: 'WA - Spokane', port: 'CA', value:	950 },
{ location: 'WY - Casper', port: 'CA', value:	1000 }
];
